### PR TITLE
fix urls

### PR DESCRIPTION
**Pull request by vtrokhymenko**

### CODE REVIEW

**Review by SemyonSinchenko — APPROVED** [review]

**Review by Yorko — APPROVED** [review]

**Comment by Yorko** [comment]
Вот все битые ссылки, как показывает  deadlinkchecker, кажется, не все еще пофикшены

404 Not Found | https://quantum-ods.github.io/qmlcourse/book/book/index.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/book/pythonblock/python_l2.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/book/pythonblock/python_l3.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/book/pythonblock/python_l4.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/book/pythonblock/python_l5.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/book/pythonblock/pythonintro.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/book/pythonblock/python_l1.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/book/prerequisite.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/book/intro1block/intro1.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/book/pythonblock/python_l7.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/book/pythonblock/python_l8.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/book/pythonblock/python_l10.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/book/pythonblock/python_l6.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/book/pythonblock/python_l9.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/book/linalgblock/intro.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/book/linalgblock/bra-ket.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/book/linalgblock/vectors.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/book/linalgblock/matrices.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/book/linalgblock/numpy.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/book/mlblock/ml_intro.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/book/qcblock/qcintro.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/book/qcblock/qubit.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/book/mlblock/ml_l1.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/book/qcblock/gates.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/book/qcblock/mixedstates.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/book/progblock/progreview.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/book/progblock/pennylane.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/book/progblock/cirq_tfq.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/book/progblock/progintro.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/book/progblock/qiskit.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/book/qcalgo/quantum_algorithms_overview.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/book/qcalgo/deutschs_algorithm.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/book/qcalgo/superdense_coding.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/book/qcalgo/quantum_teleportation.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/book/qcalgo/qcalgointro.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/book/qcalgo/grovers_algorithm.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/book/hwblock/hwintro.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/book/qcalgo/simon_algorithm.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/book/hwblock/hwreview.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/book/hwblock/scqubits.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/book/qmlkindsblock/qmlkindsintro.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/book/qmlkindsblock/hhl_algorithm.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/book/qmlkindsblock/qmlkinds.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/book/qmlkindsblock/qknn.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/book/vqcblock/vqcintro.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/book/gradsblock/gradsintro.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/book/vqcblock/vqc.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/book/qsvmblock/qsvmintro.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/book/gradsblock/gradients.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/book/qsvmblock/hybridsvm.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/book/gradsblock/hogradients.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/book/qnnblock/qnnintro.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/book/qsvmblock/classic_svm.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/book/qnnblock/qnn.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/book/qnnblock/qconv.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/book/problemsblock/problemsintro.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/book/problemsblock/quantchembasic.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/book/problemsblock/advising.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/book/problemsblock/quantchemadvancedscf.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/book/problemsblock/ising.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/book/problemsblock/copt.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/book/problems2qml/problems2qmlintro.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/book/problems2qml/np2ising.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/book/problems2qml/jordanwigner.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/book/vqeblock/vqeintro.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/book/vqeblock/tspvqe.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/vqeblock/problemsblock/ising.html | рассматривали
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/book/vqeblock/vqe.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/problems2qml/qmlkindsblock/qmlkinds.html | касались этой темы
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/book/problems2qml/eigenvals.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/book/dwaveblock/dwaveintro.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/book/qaoablock/intro.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/book/dwaveblock/dwave.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/book/qaoablock/qaoa.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/book/perspectives/academic_industrial.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/book/bibliography.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/book/authors.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/book/leaderboard.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/book/acknowledgments.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/book/glossary.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/genindex.html | link/href
404 Not Found | https://quantum-ods.github.io/qmlcourse/book/search.html | link/href

**Comment by vtrokhymenko** [comment]
видел, но не нашел их в лекциях, к примеру 
image

**Comment by Yorko** [comment]
Правильно, book нигде и нету в ссылках, это внутренние ссылки типа [тут](qcblock) перестали работать. Я поправлю, сюда же закомичу

**Review by Yorko — CHANGES_REQUESTED** [review]
Еще ссылки надо пофиксить

**Comment by vtrokhymenko** [comment]
> Правильно, book нигде и нету в ссылках, это внутренние ссылки типа `[тут](qcblock)` перестали работать. Я поправлю, сюда же закомичу

а с чего они не должны работать в таком виде? проверял часть этого и всё было норм

**Review by Yorko — APPROVED** [review]
Да, правда, это какой-то глюк [deadlinkchecker](https://www.deadlinkchecker.com/) - false positives, теперь норм должно быть

**Pull request merged**
